version: "3"
services:
  db:
      image: postgres:latest
      container_name: postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
  webapp-formation:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

#      volumes:
#        - ./data/postgres:/var/lib/postgresql/data
#      networks:
#        - postgresql-network
